language: cpp
sudo: required
dist: trusty
compiler:
- clang
- gcc
os:
- linux
before_install:
- sudo apt-get install build-essential autoconf automake cmake libboost-all-dev libconfig++-dev
- wget https://nih.at/libzip/libzip-0.11.2.tar.gz
- tar xvfp libzip-0.11.2.tar.gz
- pushd libzip-0.11.2 && ./configure --prefix=/usr && make && sudo make install
- popd
- git clone https://github.com/emweb/wt.git wt
- pushd wt;
- git checkout 4.0.4
- cmake -DCMAKE_INSTALL_PREFIX=/usr && sudo make install
- popd
script: autoreconf -vfi && ./configure && make
env:
  global:
    - MAKEFLAGS="-j 2"
